/* ── Comprehensive world languages (BCP-47) ───────────────────── */
export const WORLD_LANGUAGES = [
  { code: 'af-ZA', name: 'Afrikaans' },
  { code: 'am-ET', name: 'Amharic' },
  { code: 'ar-SA', name: 'Arabic (Saudi Arabia)' },
  { code: 'ar-EG', name: 'Arabic (Egypt)' },
  { code: 'ar-MA', name: 'Arabic (Morocco)' },
  { code: 'ar-DZ', name: 'Arabic (Algeria)' },
  { code: 'ar-TN', name: 'Arabic (Tunisia)' },
  { code: 'ar-LB', name: 'Arabic (Lebanon)' },
  { code: 'ar-JO', name: 'Arabic (Jordan)' },
  { code: 'ar-AE', name: 'Arabic (UAE)' },
  { code: 'ar-IQ', name: 'Arabic (Iraq)' },
  { code: 'ar-KW', name: 'Arabic (Kuwait)' },
  { code: 'hy-AM', name: 'Armenian' },
  { code: 'az-AZ', name: 'Azerbaijani' },
  { code: 'eu-ES', name: 'Basque' },
  { code: 'be-BY', name: 'Belarusian' },
  { code: 'bn-BD', name: 'Bengali (Bangladesh)' },
  { code: 'bn-IN', name: 'Bengali (India)' },
  { code: 'bs-BA', name: 'Bosnian' },
  { code: 'bg-BG', name: 'Bulgarian' },
  { code: 'my-MM', name: 'Burmese' },
  { code: 'ca-ES', name: 'Catalan' },
  { code: 'ceb-PH', name: 'Cebuano' },
  { code: 'zh-CN', name: 'Chinese (Simplified)' },
  { code: 'zh-TW', name: 'Chinese (Traditional)' },
  { code: 'zh-HK', name: 'Chinese (Hong Kong)' },
  { code: 'hr-HR', name: 'Croatian' },
  { code: 'cs-CZ', name: 'Czech' },
  { code: 'da-DK', name: 'Danish' },
  { code: 'nl-NL', name: 'Dutch (Netherlands)' },
  { code: 'nl-BE', name: 'Dutch (Belgium)' },
  { code: 'en-US', name: 'English (US)' },
  { code: 'en-GB', name: 'English (UK)' },
  { code: 'en-AU', name: 'English (Australia)' },
  { code: 'en-CA', name: 'English (Canada)' },
  { code: 'en-IN', name: 'English (India)' },
  { code: 'en-NZ', name: 'English (New Zealand)' },
  { code: 'en-ZA', name: 'English (South Africa)' },
  { code: 'en-IE', name: 'English (Ireland)' },
  { code: 'en-PH', name: 'English (Philippines)' },
  { code: 'en-SG', name: 'English (Singapore)' },
  { code: 'en-KE', name: 'English (Kenya)' },
  { code: 'en-NG', name: 'English (Nigeria)' },
  { code: 'en-GH', name: 'English (Ghana)' },
  { code: 'et-EE', name: 'Estonian' },
  { code: 'fil-PH', name: 'Filipino' },
  { code: 'fi-FI', name: 'Finnish' },
  { code: 'fr-FR', name: 'French (France)' },
  { code: 'fr-CA', name: 'French (Canada)' },
  { code: 'fr-BE', name: 'French (Belgium)' },
  { code: 'fr-CH', name: 'French (Switzerland)' },
  { code: 'fr-CM', name: 'French (Cameroon)' },
  { code: 'fr-SN', name: 'French (Senegal)' },
  { code: 'gl-ES', name: 'Galician' },
  { code: 'ka-GE', name: 'Georgian' },
  { code: 'de-DE', name: 'German (Germany)' },
  { code: 'de-AT', name: 'German (Austria)' },
  { code: 'de-CH', name: 'German (Switzerland)' },
  { code: 'el-GR', name: 'Greek' },
  { code: 'gu-IN', name: 'Gujarati' },
  { code: 'ht-HT', name: 'Haitian Creole' },
  { code: 'ha-NG', name: 'Hausa' },
  { code: 'he-IL', name: 'Hebrew' },
  { code: 'hi-IN', name: 'Hindi' },
  { code: 'hmn-CN', name: 'Hmong' },
  { code: 'hu-HU', name: 'Hungarian' },
  { code: 'is-IS', name: 'Icelandic' },
  { code: 'ig-NG', name: 'Igbo' },
  { code: 'id-ID', name: 'Indonesian' },
  { code: 'ga-IE', name: 'Irish' },
  { code: 'it-IT', name: 'Italian (Italy)' },
  { code: 'it-CH', name: 'Italian (Switzerland)' },
  { code: 'ja-JP', name: 'Japanese' },
  { code: 'jv-ID', name: 'Javanese' },
  { code: 'kn-IN', name: 'Kannada' },
  { code: 'kk-KZ', name: 'Kazakh' },
  { code: 'km-KH', name: 'Khmer' },
  { code: 'rw-RW', name: 'Kinyarwanda' },
  { code: 'ko-KR', name: 'Korean' },
  { code: 'ku-TR', name: 'Kurdish' },
  { code: 'ky-KG', name: 'Kyrgyz' },
  { code: 'lo-LA', name: 'Lao' },
  { code: 'lv-LV', name: 'Latvian' },
  { code: 'lt-LT', name: 'Lithuanian' },
  { code: 'lb-LU', name: 'Luxembourgish' },
  { code: 'mk-MK', name: 'Macedonian' },
  { code: 'mg-MG', name: 'Malagasy' },
  { code: 'ms-MY', name: 'Malay (Malaysia)' },
  { code: 'ms-SG', name: 'Malay (Singapore)' },
  { code: 'ml-IN', name: 'Malayalam' },
  { code: 'mt-MT', name: 'Maltese' },
  { code: 'mi-NZ', name: 'Maori' },
  { code: 'mr-IN', name: 'Marathi' },
  { code: 'mn-MN', name: 'Mongolian' },
  { code: 'ne-NP', name: 'Nepali' },
  { code: 'no-NO', name: 'Norwegian' },
  { code: 'ny-MW', name: 'Chichewa' },
  { code: 'or-IN', name: 'Odia' },
  { code: 'ps-AF', name: 'Pashto' },
  { code: 'fa-IR', name: 'Persian (Iran)' },
  { code: 'fa-AF', name: 'Persian (Afghanistan)' },
  { code: 'pl-PL', name: 'Polish' },
  { code: 'pt-BR', name: 'Portuguese (Brazil)' },
  { code: 'pt-PT', name: 'Portuguese (Portugal)' },
  { code: 'pa-IN', name: 'Punjabi (India)' },
  { code: 'pa-PK', name: 'Punjabi (Pakistan)' },
  { code: 'ro-RO', name: 'Romanian' },
  { code: 'ru-RU', name: 'Russian' },
  { code: 'sm-WS', name: 'Samoan' },
  { code: 'sr-RS', name: 'Serbian' },
  { code: 'st-ZA', name: 'Sesotho' },
  { code: 'sn-ZW', name: 'Shona' },
  { code: 'sd-PK', name: 'Sindhi' },
  { code: 'si-LK', name: 'Sinhala' },
  { code: 'sk-SK', name: 'Slovak' },
  { code: 'sl-SI', name: 'Slovenian' },
  { code: 'so-SO', name: 'Somali' },
  { code: 'es-ES', name: 'Spanish (Spain)' },
  { code: 'es-MX', name: 'Spanish (Mexico)' },
  { code: 'es-AR', name: 'Spanish (Argentina)' },
  { code: 'es-CO', name: 'Spanish (Colombia)' },
  { code: 'es-CL', name: 'Spanish (Chile)' },
  { code: 'es-PE', name: 'Spanish (Peru)' },
  { code: 'es-VE', name: 'Spanish (Venezuela)' },
  { code: 'es-US', name: 'Spanish (US)' },
  { code: 'su-ID', name: 'Sundanese' },
  { code: 'sw-KE', name: 'Swahili (Kenya)' },
  { code: 'sw-TZ', name: 'Swahili (Tanzania)' },
  { code: 'sv-SE', name: 'Swedish' },
  { code: 'tg-TJ', name: 'Tajik' },
  { code: 'ta-IN', name: 'Tamil (India)' },
  { code: 'ta-LK', name: 'Tamil (Sri Lanka)' },
  { code: 'ta-MY', name: 'Tamil (Malaysia)' },
  { code: 'ta-SG', name: 'Tamil (Singapore)' },
  { code: 'tt-RU', name: 'Tatar' },
  { code: 'te-IN', name: 'Telugu' },
  { code: 'th-TH', name: 'Thai' },
  { code: 'ti-ET', name: 'Tigrinya' },
  { code: 'tr-TR', name: 'Turkish' },
  { code: 'tk-TM', name: 'Turkmen' },
  { code: 'uk-UA', name: 'Ukrainian' },
  { code: 'ur-PK', name: 'Urdu (Pakistan)' },
  { code: 'ur-IN', name: 'Urdu (India)' },
  { code: 'ug-CN', name: 'Uyghur' },
  { code: 'uz-UZ', name: 'Uzbek' },
  { code: 'vi-VN', name: 'Vietnamese' },
  { code: 'cy-GB', name: 'Welsh' },
  { code: 'xh-ZA', name: 'Xhosa' },
  { code: 'yi-001', name: 'Yiddish' },
  { code: 'yo-NG', name: 'Yoruba' },
  { code: 'zu-ZA', name: 'Zulu' },
]
